vim.opt.rtp:append(vim.fn.getcwd())
local edit = require("pair.edit")

local function reset(lines)
  edit.dismiss_answer()
  if edit.pending() then edit.accept() end
  vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
end

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 2, 1 })
vim.cmd("normal! v2l\27")
local selected = assert(edit.selection())
assert(selected.original == "eta", "character selection should capture exact text")
assert(edit.show(selected, "ETA"))
assert(vim.api.nvim_buf_get_lines(0, 1, 2, false)[1] == "bETA", "proposal should appear in the unsaved buffer immediately")
local control_ns = vim.api.nvim_get_namespaces()["pair.nvim.control"]
local controls = vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, { details = true })
assert(#controls == 1 and controls[1][4].virt_lines_above, "proposal controls should appear above the changed code")
assert(#vim.api.nvim_list_wins() == 1, "proposal controls should not open a floating window")
assert(vim.api.nvim_win_get_cursor(0)[1] == 1, "cursor should stay above the changed code")
assert(edit.accept())
assert(#vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, {}) == 0, "accept should remove controls")
assert(vim.api.nvim_buf_get_lines(0, 1, 2, false)[1] == "bETA", "accept should keep the proposal")

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! Vj\27")
selected = assert(edit.selection())
assert(selected.original == "alpha\nbeta", "line selection should include both lines")
assert(edit.show(selected, "one\ntwo"))
assert(table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "|") == "one|two|gamma", "line proposal should edit the buffer")
assert(edit.reject())
assert(table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "|") == "alpha|beta|gamma", "reject must restore the original lines")

vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! Vj\27")
selected = assert(edit.selection())
assert(edit.show(selected, ""))
assert(edit.accept())
assert(table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "|") == "gamma", "empty linewise replacement should delete selected lines")

reset({ "one", "two" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! Vj\27")
selected = assert(edit.selection())
assert(edit.show(selected, ""))
assert(edit.reject())
assert(table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "|") == "one|two", "reject should restore a whole-buffer deletion")

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
local insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
assert(vim.api.nvim_buf_get_lines(0, 1, 2, false)[1] == "new code", "insertion should appear in the buffer")
assert(vim.api.nvim_win_get_cursor(0)[1] == 1, "insert should leave cursor on the line above the insertion")
local function press(key)
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, false, true), "x", false)
  vim.wait(50)
end
press("j")
assert(#vim.api.nvim_list_wins() == 2 and edit.pending().choice == 1, "j should place the real cursor on Accept")
press("l")
assert(edit.pending().choice == 2, "l should select Reject")
press("<CR>")
assert(not edit.pending(), "Enter should choose the focused control")
assert(table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "|") == "alpha|beta|gamma", "reject should restore an insertion")
assert(#vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, {}) == 0, "reject should remove inline controls")

vim.api.nvim_win_set_cursor(0, { 2, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "accepted code\n"))
press("j")
press("<CR>")
assert(not edit.pending(), "Enter should accept the focused Accept control")
assert(vim.api.nvim_buf_get_lines(0, 1, 2, false)[1] == "accepted code", "keyboard accept should keep inserted code")
assert(#vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, {}) == 0, "accept should remove the virtual control row")

reset({ "one", "two", "three", "four" })
vim.api.nvim_win_set_cursor(0, { 3, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
assert(vim.api.nvim_win_get_cursor(0)[1] == 2, "cursor should start one real line above this insertion")
press("j")
assert(#vim.api.nvim_list_wins() == 2, "j should focus an inline control with a real cursor")
press("k")
assert(#vim.api.nvim_list_wins() == 1 and vim.api.nvim_win_get_cursor(0)[1] == 2, "k should leave the controls above the insertion")
press("k")
assert(vim.api.nvim_win_get_cursor(0)[1] == 1, "a second k should move normally above the controls")
assert(edit.reject())

reset({ "one", "two", "three", "four", "five" })
vim.api.nvim_win_set_cursor(0, { 3, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "helper()\n", nil,
  "This helper keeps the call site small and makes the behavior easier to reuse."))
controls = vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, { details = true })
assert(#controls[1][4].virt_lines > 2 and controls[1][4].virt_lines[1][1][2] == "PairRationale",
  "the proposal rationale should wrap above the controls")
press("j")
press("j")
assert(vim.api.nvim_win_get_cursor(0)[1] == 3, "j from controls should enter the proposed code")
press("k")
assert(vim.api.nvim_get_current_win() ~= insertion.source_win and #vim.api.nvim_list_wins() == 2,
  "k from the first proposed line should re-enter the controls")
press("k")
assert(vim.api.nvim_win_get_cursor(0)[1] == 2, "k from controls should leave above the proposal")
press("j")
assert(#vim.api.nvim_list_wins() == 2, "j should re-enter controls after leaving above")
press("j")
vim.api.nvim_buf_set_lines(0, 0, 0, false, { "added before proposal" })
local anchor_ns = vim.api.nvim_get_namespaces()["pair.nvim.control_anchor"]
local anchor = vim.api.nvim_buf_get_extmarks(0, anchor_ns, 0, -1, {})[1]
assert(anchor and anchor[2] == 3, "control anchor should follow edits before the proposal")
vim.api.nvim_win_set_cursor(0, { 4, 0 })
press("k")
assert(#vim.api.nvim_list_wins() == 2, "k should re-enter controls after an earlier buffer edit")
press("j")
assert(edit.accept())

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
vim.api.nvim_buf_set_lines(0, 0, 1, false, { "changed" })
assert(not edit.reject(), "reject should not erase user edits made after the proposal")
assert(edit.accept(), "accept should keep user edits")

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "saved code\n"))
local temporary = vim.fn.tempname() .. ".lua"
vim.api.nvim_buf_set_name(0, temporary)
vim.cmd("write")
assert(not edit.pending(), "saving should accept the pending proposal")
assert(table.concat(vim.fn.readfile(temporary), "|"):find("saved code", 1, true), "saved file should contain the proposal")
vim.fn.delete(temporary)

reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
vim.cmd("normal! V\27")
selected = assert(edit.selection())
edit.start_progress(selected, "ask")
local progress_ns = vim.api.nvim_get_namespaces()["pair.nvim.progress"]
assert(#vim.api.nvim_buf_get_extmarks(0, progress_ns, 0, -1, {}) == 1,
  "Ask should show a compact spinner without adding virtual answer lines while waiting")
assert(edit.show_answer(selected, string.rep("a long explanation ", 12), false), "streamed answer should attach to buffer")
assert(#vim.api.nvim_buf_get_extmarks(0, progress_ns, 0, -1, {}) == 0,
  "streamed answer should replace the loading spinner")
local answer_ns = vim.api.nvim_get_namespaces()["pair.nvim.answer"]
local marks = vim.api.nvim_buf_get_extmarks(0, answer_ns, 0, -1, { details = true })
assert(#marks == 1 and #marks[1][4].virt_lines > 2, "answer should wrap across virtual lines")
assert(marks[1][4].virt_lines[1][1][2] == "PairAnswerTitle", "answer should have a styled header")
assert(marks[1][4].virt_lines[1][3][2] == "PairAnswerClose", "answer should expose a clickable close control")
assert(marks[1][4].virt_lines[1][3][1] == " × ", "close control should have equal padding on both sides")
assert(marks[1][4].virt_lines[2][1][2] == "PairAnswer", "answer body should use the highlighted background")
assert(edit.show_answer(selected, string.rep("a long explanation ", 12), true), "answer should finish")
vim.api.nvim_win_set_cursor(0, { 3, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
assert(#vim.api.nvim_buf_get_extmarks(0, answer_ns, 0, -1, {}) == 0,
  "starting a proposal should remove an older Ask annotation")
assert(edit.accept())
assert(#vim.api.nvim_buf_get_extmarks(0, control_ns, 0, -1, {}) == 0,
  "accepting should remove temporary control lines")

vim.api.nvim_win_set_cursor(0, { 1, 0 })
insertion = edit.insertion()
edit.start_progress(insertion, "edit")
assert(#vim.api.nvim_buf_get_extmarks(0, progress_ns, 0, -1, {}) == 1, "edit request should show in-buffer progress")
edit.stop_progress()
vim.api.nvim_buf_set_lines(0, 0, 1, false, { "changed" })
local ok = edit.show(insertion, "new code")
assert(not ok, "stale proposals should not be shown")

reset({ "one", "two", "three" })
local original_j = function() end
vim.keymap.set("n", "j", original_j, { buffer = 0, silent = true })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
assert(edit.accept())
assert(vim.fn.maparg("j", "n", false, true).callback == original_j,
  "closing a proposal should restore an existing buffer-local motion mapping")
vim.keymap.del("n", "j", { buffer = 0 })

-- Visual-mode ':' adds '<,'> to the command. Both selection commands must accept it.
local pair = require("pair")
pair.setup({ keymaps = false })
local asked, changed
pair.ask = function(message)
  asked = { message = message, target = assert(edit.selection()) }
end
pair.change = function(message)
  changed = { message = message, target = assert(edit.selection()) }
end
reset({ "alpha", "beta", "gamma" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! Vj\27")
vim.cmd("'<,'>PairAsk why is this here")
assert(asked.message == "why is this here" and asked.target.original == "alpha\nbeta", "PairAsk should accept a visual range")
vim.cmd("'<,'>PairChange simplify this")
assert(changed.message == "simplify this" and changed.target.original == "alpha\nbeta", "PairChange should accept a visual range")

local ui = require("pair.ui")
local source_win = vim.api.nvim_get_current_win()
ui.chat()
vim.api.nvim_set_current_win(source_win)
vim.wait(30)
assert(vim.api.nvim_get_mode().mode == "n", "opening chat must not leave source in Insert mode")
reset({ "one", "two", "three", "four" })
vim.api.nvim_win_set_cursor(source_win, { 3, 0 })
insertion = edit.insertion()
assert(edit.show(insertion, "new code\n"))
press("j")
assert(vim.api.nvim_get_current_win() ~= source_win, "controls should take focus with chat open")
press("l")
assert(edit.pending().choice == 2, "controls should move to Reject with chat open")
press("k")
assert(vim.api.nvim_get_current_win() == source_win and vim.api.nvim_win_get_cursor(source_win)[1] == 2,
  "leaving controls should restore source focus with chat open")
press("k")
assert(vim.api.nvim_win_get_cursor(source_win)[1] == 1, "source motions should resume above controls")
assert(edit.reject())
assert(#vim.api.nvim_list_wins() == 4, "reject should leave only source and Pair windows")
ui.close()

print("Pair edit tests passed")
