local pair = require("pair")
pair.setup({ keymaps = false })
assert(vim.fn.exists(":PairChat") == 2)
assert(vim.fn.exists(":PairAsk") == 2)
assert(vim.fn.exists(":PairHere") == 2)
assert(#vim.api.nvim_get_runtime_file("doc/pair.txt", false) > 0)
vim.cmd.helptags(vim.env.PAIR_TEST_PLUGIN_ROOT .. "/doc")
vim.cmd("help pair")
assert(vim.bo.filetype == "help")
vim.cmd("helpclose")
pair.toggle_chat()
assert(require("pair.ui").is_open())
pair.toggle_chat()
assert(not require("pair.ui").is_open())
print("Pair clean install smoke check passed")
